//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashReportingTool.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BatchMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BatchMaster()
        {
            this.CandidateBatchMasters = new HashSet<CandidateBatchMaster>();
            this.SessionMasters = new HashSet<SessionMaster>();
        }

        public int BatchId { get; set; }
        public string BatchName { get; set; }
        public int RefExpertName { get; set; }
        [DataType(DataType.Time)]
        public System.TimeSpan StartTime { get; set; }
        [DataType(DataType.Time)]
        public System.TimeSpan EndTime { get; set; }

        public System.DateTime StartDate { get; set; }
        public System.DateTime CompletedDate { get; set; }
        public int BatchStatus { get; set; }
        public string Technology { get; set; }

        public virtual StatusMaster StatusMaster { get; set; }
        public virtual ExpertMaster ExpertMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateBatchMaster> CandidateBatchMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionMaster> SessionMasters { get; set; }
    }
}
