//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashReportingTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateCourseMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CandidateCourseMaster()
        {
            this.CandidateBatchMasters = new HashSet<CandidateBatchMaster>();
        }
    
        public int CCId { get; set; }
        public int RefCandidateTitle { get; set; }
        public int RefCourseTitle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateBatchMaster> CandidateBatchMasters { get; set; }
        public virtual CandidateMaster CandidateMaster { get; set; }
        public virtual CourseMaster CourseMaster { get; set; }
    }
}
