//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashReportingTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseMaster()
        {
            this.CandidateCourseMasters = new HashSet<CandidateCourseMaster>();
        }
    
        public int CourseId { get; set; }
        public string CourseTitle { get; set; }
        public int Duration { get; set; }
        public decimal Fees { get; set; }
        public string CourseContent { get; set; }
        public bool IsCourseEnabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateCourseMaster> CandidateCourseMasters { get; set; }
    }
}
