//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashReportingTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpertMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExpertMaster()
        {
            this.TechExpertMasters = new HashSet<TechExpertMaster>();
            this.BatchMasters = new HashSet<BatchMaster>();
            this.TaskMasters = new HashSet<TaskMaster>();
            this.TaskMasters1 = new HashSet<TaskMaster>();
            this.LoginLogMasters = new HashSet<LoginLogMaster>();
        }
    
        public int ExpertId { get; set; }
        public string ExpertName { get; set; }
        public string ExpertPassword { get; set; }
        public string ExpertEmailid { get; set; }
        public string ExpertMobile { get; set; }
        public string Designation { get; set; }
        public Nullable<int> RefLocationId { get; set; }
    
        public virtual LocationMaster LocationMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TechExpertMaster> TechExpertMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchMaster> BatchMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskMaster> TaskMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskMaster> TaskMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginLogMaster> LoginLogMasters { get; set; }
    }
}
