//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashReportingTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginLogMaster
    {
        public int logid { get; set; }
        public Nullable<System.TimeSpan> login { get; set; }
        public Nullable<System.TimeSpan> logout { get; set; }
        public Nullable<System.DateTime> logdate { get; set; }
        public int expertId { get; set; }
        public string status { get; set; }
    
        public virtual ExpertMaster ExpertMaster { get; set; }
    }
}
