//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashReportingTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskMaster
    {
        public int TaskId { get; set; }
        public System.DateTime TaskDate { get; set; }
        public bool TaskDone { get; set; }
        public int RefExpertName { get; set; }
        public string TaskDetails { get; set; }
        public int RefTaskTitle { get; set; }
        public int EstimateTime { get; set; }
        public Nullable<System.TimeSpan> TaskStartTime { get; set; }
        public Nullable<System.TimeSpan> TaskEndTime { get; set; }
        public Nullable<int> TimeTaken { get; set; }
        public Nullable<int> RefAssignedBy { get; set; }
        public Nullable<bool> AssignedTask { get; set; }
        public Nullable<bool> IsStartedTask { get; set; }
        public Nullable<System.DateTime> DeadLine { get; set; }
    
        public virtual ExpertMaster ExpertMaster { get; set; }
        public virtual ExpertMaster ExpertMaster1 { get; set; }
        public virtual TaskTitleMaster TaskTitleMaster { get; set; }
    }
}
