//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashReportingTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechExpertMaster
    {
        public int TechExpertId { get; set; }
        public int RefTechId { get; set; }
        public int RefExpertId { get; set; }
        public bool TechExpertIsEnabled { get; set; }
    
        public virtual ExpertMaster ExpertMaster { get; set; }
        public virtual TechMaster TechMaster { get; set; }
    }
}
